http:
  listener:
    port: "8081"
    host: "0.0.0.0"
    path: "/migration"
sfdc:
  username: "![ieuxPuhLYAImqDJ91tinOielNowbcMtk]"
  password: "![NxIv3MJyqtzksEHDU+r5fg==]"
  securitytoken: "![BV2BGKOSssfGUDZ9JnjWZd6hfKGVE7yRQziiZP5qI2g=]"
  
db:
  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "![ltYXHZgBunp+B2BZ5+ulAA==]"
    database: "sfdc"